[package]
name = "sqlite3-vfs-mem"
description = "SQLite3-rs: in-memory VFS (for :memory: databases and tests)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlite3-vfs = { path = "../sqlite3-vfs" }
thiserror.workspace = true
parking_lot.workspace = true
