[package]
name = "sqlite3-pager"
description = "SQLite3-rs: page cache, WAL, and rollback journal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlite3-vfs = { path = "../sqlite3-vfs" }
sqlite3-alloc = { path = "../sqlite3-alloc" }
sqlite3-sync = { path = "../sqlite3-sync" }
thiserror.workspace = true
parking_lot.workspace = true
getrandom.workspace = true

[dev-dependencies]
tempfile.workspace = true
