[package]
name = "sqlite3-codegen"
description = "SQLite3-rs: VDBE bytecode generator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlite3-ast = { path = "../sqlite3-ast" }
sqlite3-schema = { path = "../sqlite3-schema" }
sqlite3-optimizer = { path = "../sqlite3-optimizer" }
sqlite3-vdbe = { path = "../sqlite3-vdbe" }
thiserror.workspace = true
