[package]
name = "sqlite3-ffi"
description = "SQLite3-rs: #[no_mangle] C ABI compatibility layer"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
sqlite3_crate = { path = "../sqlite3", package = "sqlite3" }
thiserror.workspace = true
