[package]
name = "sqlite3-vfs-unix"
description = "SQLite3-rs: Unix VFS implementation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlite3-vfs = { path = "../sqlite3-vfs" }
thiserror.workspace = true
memmap2.workspace = true
bitflags.workspace = true

[target.'cfg(unix)'.dependencies]
# libc is needed for POSIX advisory locks
libc = "0.2"
getrandom = { workspace = true }

[dev-dependencies]
tempfile.workspace = true
