[package]
name = "sqlite3-parser"
description = "SQLite3-rs: SQL parser producing an AST"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlite3-tokenizer = { path = "../sqlite3-tokenizer" }
sqlite3-ast = { path = "../sqlite3-ast" }
thiserror.workspace = true
