[package]
name = "sqlite3-functions"
description = "SQLite3-rs: built-in SQL functions"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlite3-vdbe = { path = "../sqlite3-vdbe" }
sqlite3-record = { path = "../sqlite3-record" }
thiserror.workspace = true
chrono = "0.4.44"
