[package]
name = "sqlite3-optimizer"
description = "SQLite3-rs: query planner (WHERE analysis, index selection)"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlite3-ast = { path = "../sqlite3-ast" }
sqlite3-schema = { path = "../sqlite3-schema" }
thiserror.workspace = true
